<a href="https://colab.research.google.com/github/karthikkoding/pytorch_for_DL_ML/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

resource Notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

github - Q&A : https://github.com/mrdbourke/pytorch-deep-learning

In [ ]:
print("i am excited to write pytorch code")

i am excited to write pytorch code


In [ ]:
!nvidia-smi

Wed Mar 20 19:04:04 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   44C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


##Introduction to tensor
##creating tensors

Pytorch tensors are created using `torch.Tensor()`

Link : https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
 scalar.ndim

0

In [ ]:
 scalar.item()

7

In [ ]:
# Vector

vector = torch.tensor([[7,7],[8,9]])
vector

tensor([[7, 7],
        [8, 9]])

In [ ]:
vector.shape

torch.Size([2, 2])

In [ ]:
##MATRIX

matrix = torch.tensor([[7,8],[7,9]])
matrix

tensor([[7, 8],
        [7, 9]])

In [ ]:
matrix.ndim

2

In [ ]:
##TENSOR

TENSOR = torch.tensor([[[1,2,3],
                        [1,2,3],
                        [6,7,8]],
                       [[4,5,6],
                        [8,9,10],
                        [6,7,8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [1, 2, 3],
        [6, 7, 8]])

###Random Tensors

Why random tensors?

random tensors are important because the way many neural networks is that they start with tensors full of random numbers and then adjust those random number to better represent the data

`start with random number -> look at data -> update random numbers -> look at data -> update`

In [ ]:
##create Random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor



tensor([[0.1375, 0.0729, 0.0930, 0.5773],
        [0.4853, 0.2798, 0.9401, 0.8550],
        [0.8457, 0.4795, 0.8986, 0.3237]])

In [ ]:
random_tensor.ndim

2

In [ ]:
##create Random tensors similar to image tensor

random_image_size_tensor = torch.rand(size=(225,225,3))
random_image_size_tensor

tensor([[[0.2754, 0.5571, 0.2137],
         [0.0427, 0.4696, 0.7816],
         [0.6050, 0.3738, 0.6177],
         ...,
         [0.4586, 0.9641, 0.3775],
         [0.6335, 0.8021, 0.2228],
         [0.4926, 0.1051, 0.5373]],

        [[0.9205, 0.8345, 0.0211],
         [0.1308, 0.0936, 0.0182],
         [0.0104, 0.0705, 0.6044],
         ...,
         [0.4950, 0.1214, 0.5472],
         [0.0687, 0.9645, 0.8383],
         [0.9666, 0.5383, 0.7191]],

        [[0.2092, 0.4535, 0.8466],
         [0.9504, 0.7941, 0.7843],
         [0.8121, 0.7559, 0.5102],
         ...,
         [0.8094, 0.4211, 0.1484],
         [0.8064, 0.6886, 0.0459],
         [0.5265, 0.5092, 0.2789]],

        ...,

        [[0.2450, 0.8734, 0.6113],
         [0.5003, 0.1273, 0.9486],
         [0.7595, 0.4493, 0.5113],
         ...,
         [0.7470, 0.5975, 0.2626],
         [0.1383, 0.5437, 0.0846],
         [0.3945, 0.2010, 0.8906]],

        [[0.2859, 0.1953, 0.6878],
         [0.4694, 0.6616, 0.6727],
         [0.

### zeros and ones

In [ ]:
# create a tensor of all zeros

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all zeros

ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Creating a range of tensors and tensor-like

In [ ]:
#create a range of tensors

one_to_ten = torch.arange(0,10,1)

In [ ]:
#creating a tensors-like
#we want to replicate from something else which is already created

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

In [ ]:
# create tensor of different datatypes
#default is float32
float_32_tensor = torch.tensor([3.0,6,9],dtype=None)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0,6,9],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor_2 = float_32_tensor.type(torch.int32)

In [ ]:
float_16_tensor_2

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_16_tensor_2*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
#create a tensor and try to get 3 error above errors

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7293, 0.5193, 0.7770, 0.9064],
        [0.0515, 0.1474, 0.6579, 0.5967],
        [0.6747, 0.6462, 0.6303, 0.4621]])

In [ ]:
#findout details about tensor

print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor : {some_tensor.device}")

tensor([[0.7293, 0.5193, 0.7770, 0.9064],
        [0.0515, 0.1474, 0.6579, 0.5967],
        [0.6747, 0.6462, 0.6303, 0.4621]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


###Manipulating tensor (tensor operations)

Tensor operations include

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication


In [ ]:
# Addition

tensor = torch.tensor([1,2,3])

tensor + 100

tensor([101, 102, 103])

In [ ]:
# Multiplication

tensor = torch.tensor([1,2,3])

tensor * 100

tensor([100, 200, 300])

In [ ]:
tensor1 = torch.rand([3,4])
tensor2 = torch.rand([3,4])
tensor3 = torch.rand([4,5])
tensor4 = torch.rand([1,3])
tensor5 = torch.rand([3,1])

In [ ]:
tensor1*tensor2

tensor([[0.5010, 0.7421, 0.1559, 0.0993],
        [0.8096, 0.1741, 0.0154, 0.3143],
        [0.3164, 0.1870, 0.0463, 0.3505]])

In [ ]:
#Try out inbuilt functions

torch.mul(tensor1,10)
torch.add(tensor1,10)
torch.sub(tensor1,10)


tensor([[-9.4539, -9.9706, -9.1840, -9.0904],
        [-9.8869, -9.4221, -9.9756, -9.8368],
        [-9.2488, -9.5353, -9.5504, -9.3098]])

###Matrix multiplication

Two main ways of performing multiplication in deep learning

1. Element Wise
2. Matrix Multiplication (Dot Product)

There are two major rules for matrix multiplication

* The **inner dimensions** must match
* The resulting matrix has the shape of **outer dimensions**

In [ ]:
%%time
torch.matmul(tensor1 , tensor3)

CPU times: user 0 ns, sys: 556 µs, total: 556 µs
Wall time: 415 µs


tensor([[0.8001, 1.5474, 1.1438, 0.8164, 0.5319],
        [1.2164, 1.3481, 1.4024, 1.0017, 0.8807],
        [0.9934, 1.1375, 1.4325, 0.9857, 1.0746]])

In [ ]:
tensor4.ndim

2

In [ ]:
tensor = torch.tensor([1, 2, 3])

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 0 ns, sys: 94 µs, total: 94 µs
Wall time: 98.9 µs


tensor(14)

In [ ]:
tensor.ndim

3

##One of the Most common errors in Deep learning : Shape errors


# shapes for matrix multiplications

usually can be solved with traspose using .T

## Finding the min, max,sum ,ect (tensor aggregration)

and also positional aggregations (argmin, argmax)


In [ ]:
x= torch.rand([10])
x

tensor([0.2814, 0.1392, 0.5438, 0.9892, 0.5193, 0.5823, 0.9790, 0.3954, 0.3248,
        0.1511])

In [ ]:
x = x.type(torch.float32)

In [ ]:
x.min(), x.max(), x.mean(), x.sum(), x.argmax(), x.argmin()

(tensor(0.1392),
 tensor(0.9892),
 tensor(0.4906),
 tensor(4.9055),
 tensor(3),
 tensor(1))

In [ ]:
torch.min(x)

tensor(0.1392)

### Reshaping, viewing and stacking , squeezing and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other vstack or hstack
* Squeeze - removes all `1` dimesnions from a tensor
* Unsqueeze - add `1` dimesnions to a tensor
* Permute - return a view of input with dimensions permuted (swapped) in a certain way

In [ ]:
# create a tensor and reshape

x = torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
# add a extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view
z= x.view(9,1)
z, z.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [ ]:
z[:,0]=5

In [ ]:
z,x

(tensor([[5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5]]),
 tensor([5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [ ]:
# Stack tensors on  top of each other
x_stacked = torch.stack([x,x*2,x*3,x*4],dim=-2)
x.shape,x_stacked.shape

(torch.Size([9]), torch.Size([4, 9]))

In [ ]:
x_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
        [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
        [ 4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [ ]:
#squeeze and unsqueeze
#torch.squeeze() removes all single dimensions from the target tensor


x_reshaped,x_reshaped.shape,x_reshaped.squeeze().shape

(tensor([[5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5],
         [5]]),
 torch.Size([9, 1]),
 torch.Size([9]))

In [ ]:
print(f"Previous tensor : {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")


print(f"squeezed tensor : {x_reshaped.squeeze()}")
print(f"squeezed tensor shape : {x_reshaped.squeeze().shape}")

Previous tensor : tensor([[5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5],
        [5]])
Previous shape : torch.Size([9, 1])
squeezed tensor : tensor([5, 5, 5, 5, 5, 5, 5, 5, 5])
squeezed tensor shape : torch.Size([9])


In [ ]:
x = torch.zeros(2, 1, 2, 1, 2,1)
x.size()


torch.Size([2, 1, 2, 1, 2, 1])

In [ ]:
y = torch.squeeze(x)
y.size()


torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2, 1])

In [ ]:
y = torch.squeeze(x, 1)
y.size()


torch.Size([2, 2, 1, 2, 1])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
y.shape

torch.Size([2, 2, 2, 1])

In [ ]:
##permute - rearrange the dimesions of target tensor in a sepcified manner

x = torch.randn(2, 3, 5)
x.size()
x

tensor([[[ 2.3767e-03,  1.4276e+00,  1.4352e+00, -4.3201e-01, -2.8814e-01],
         [-2.6470e-04,  1.0396e+00, -4.1431e-02,  1.5747e+00,  4.0900e-01],
         [ 9.4293e-01,  2.2981e-03, -4.2279e-01,  2.7503e+00, -4.8245e-01]],

        [[-5.7717e-01, -1.2610e+00, -9.4321e-01, -5.3589e-01,  2.6051e-01],
         [ 1.0684e+00, -3.7817e-01, -4.0443e-01,  1.2317e+00,  8.0711e-01],
         [ 5.6162e-01, -6.1543e-01, -5.4270e-02, -9.7147e-01,  1.2718e+00]]])

In [ ]:
torch.permute(x, (2, 0, 1)).size()


torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size=(224,224,3))

In [ ]:
x_permutted = torch.permute(x_original,(2,1,0))

In [ ]:
x_original.shape, x_permutted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing ( selecting data from tensors)


this is same as Numpy

In [ ]:
x= torch.rand(1,9).reshape(1,3,3)
x[0]

tensor([[0.2290, 0.9721, 0.1688],
        [0.5011, 0.8008, 0.9928],
        [0.9517, 0.1485, 0.0411]])

In [ ]:
x[0,2,2]

tensor(0.0411)

In [ ]:
x[:,:,1]

tensor([[0.9721, 0.8008, 0.1485]])

In [ ]:
x[:,1,1].ndim

1

In [ ]:
x[0,1,1].ndim

0

In [ ]:
x[:,:,2]

tensor([[0.1688, 0.9928, 0.0411]])

##PyTorch tensors and Numpy

Numpy is numerical computing library

* Data in Numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* Pytorch tensor to numpy -> torch.Tensor.numpy()


Note : deafult datatype in numpy is float64, where is tensor in torch is float32, so if we are converting it from numpy to tensor, it will have float64 or vice versa

In [ ]:
array = np.arange(1.0,8.0,1)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)

In [ ]:
tensor = tensor.numpy()

array([1., 2., 3., 4., 5., 6., 7.], dtype=float32)

## PyTorch Reproducibility

Trying to take the random out of random, in short how a neural networks learns is:

`start with random number-> perform tensor operations->update random numbers->again->again->again....`

to reduce the randomness in nn and pytorch, there comes the concepts of ***random seed***

essentially what random seed does is "flavour" the randomness

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

In [ ]:
random_tensor_A,random_tensor_B,(random_tensor_B==random_tensor_A)

(tensor([[0.8445, 0.8708, 0.3790, 0.8386],
         [0.9703, 0.3979, 0.9879, 0.2237],
         [0.0186, 0.2187, 0.7407, 0.0658]]),
 tensor([[0.3423, 0.3737, 0.0462, 0.2384],
         [0.4945, 0.4014, 0.2875, 0.0135],
         [0.7122, 0.4547, 0.9200, 0.0840]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
#lets create tensors which are reprodicible

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

random_tensor_C,random_tensor_D,(random_tensor_C==random_tensor_D)

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

##Running tensors on GPUs (and making faster computations)
Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.

##1. Getting a GPU
You may already know what's going on when I say GPU. But if not, there are a few ways to get access to one.

Method	Difficulty to setup	Pros	Cons	How to setup
Google Colab	Easy	Free to use, almost zero setup required, can share work with others as easy as a link	Doesn't save your data outputs, limited compute, subject to timeouts	Follow the Google Colab Guide
Use your own	Medium	Run everything locally on your own machine	GPUs aren't free, require upfront cost	Follow the PyTorch installation guidelines
Cloud computing (AWS, GCP, Azure)	Medium-Hard	Small upfront cost, access to almost infinite compute	Can get expensive if running continually, takes some time to setup right	Follow the PyTorch installation guidelines
There are more options for using GPUs but the above three will suffice for now.

Personally, I use a combination of Google Colab and my own personal computer for small scale experiments (and creating this course) and go to cloud resources when I need more compute power.

Resource: If you're looking to purchase a GPU of your own but not sure what to get, Tim Dettmers has an excellent guide.

To check if you've got access to a Nvidia GPU, you can run !nvidia-smi where the ! (also called bang) means "run this on the command line".

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup devive agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count the number of devices

torch.cuda.device_count()

1

##Device-agnostic code
Due to the structure of PyTorch, you may need to explicitly write device-agnostic (CPU or GPU) code; an example may be creating a new tensor as the initial hidden state of a recurrent neural network.

The first step is to determine whether the GPU should be used or not. A common pattern is to use Python’s argparse module to read in user arguments, and have a flag that can be used to disable CUDA, in combination with is_available(). In the following, args.device results in a torch.device object that can be used to move tensors to CPU or CUDA.
import argparse
import torch

parser = argparse.ArgumentParser(description='PyTorch Example')
parser.add_argument('--disable-cuda', action='store_true',
                    help='Disable CUDA')
args = parser.parse_args()
args.device = None
if not args.disable_cuda and torch.cuda.is_available():
    args.device = torch.device('cuda')
else:
    args.device = torch.device('cpu')

##Setting up device agnostic code

Putting tensor and models on GPU


Bydefault they will be on CPU

In [ ]:
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor, tensor.device,tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]),
 device(type='cpu'),
 tensor([1, 2, 3], device='cuda:0'),
 device(type='cuda', index=0))

(tensor([1, 2, 3]), device(type='cpu'))

Numpy only works on CPU

so we have to move tensors back to GPU

In [ ]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
#resolution

tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

##Exercises :